"""Roster of students used for seat shuffling and chart generation.

Each entry defines the serial number (整理番号), school ID, name in
Kanji and kana, and the enrolment status.  Only students with status
"在籍" are used when shuffling seats.
"""

STUDENTS = [
    {"serial": 1, "student_id": "23201", "name_kanji": "浅野 悠里子", "name_kana": "あさの ゆりこ", "status": "在籍", "gender": "F"},
    {"serial": 2, "student_id": "23202", "name_kanji": "池田 光駕", "name_kana": "いけだ こうが", "status": "在籍", "gender": "M"},
    {"serial": 3, "student_id": "23203", "name_kanji": "石川 蓮稀", "name_kana": "いしかわ はずき", "status": "在籍", "gender": "M"},
    {"serial": 4, "student_id": "23204", "name_kanji": "石川 未桜", "name_kana": "いしかわ みお", "status": "在籍", "gender": "F"},
    {"serial": 5, "student_id": "23207", "name_kanji": "遠藤 杏", "name_kana": "えんどう あんず", "status": "在籍", "gender": "F"},
    {"serial": 6, "student_id": "23208", "name_kanji": "生沼 萊", "name_kana": "おいぬま らい", "status": "在籍", "gender": "M"},
    {"serial": 7, "student_id": "23209", "name_kanji": "大嶋 治斗", "name_kana": "おおしま はると", "status": "在籍", "gender": "M"},
    {"serial": 8, "student_id": "23210", "name_kanji": "大谷 律月", "name_kana": "おおたに りつき", "status": "在籍", "gender": "M"},
    {"serial": 9, "student_id": "23211", "name_kanji": "落合 佑要", "name_kana": "おちあい ゆい", "status": "在籍", "gender": "M"},
    {"serial": 10, "student_id": "23212", "name_kanji": "金子 光", "name_kana": "かねこ ひかる", "status": "在籍", "gender": "M"},
    {"serial": 11, "student_id": "23213", "name_kanji": "川田 律貴", "name_kana": "かわだ りつき", "status": "在籍", "gender": "M"},
    {"serial": 12, "student_id": "23215", "name_kanji": "熊井 悠太", "name_kana": "くまい ゆうた", "status": "在籍", "gender": "M"},
    {"serial": 13, "student_id": "23216", "name_kanji": "熊谷 光紘", "name_kana": "くまがい みひろ", "status": "在籍", "gender": "M"},
    {"serial": 14, "student_id": "23217", "name_kanji": "倉田 楽翔", "name_kana": "くらた がくと", "status": "在籍", "gender": "M"},
    {"serial": 15, "student_id": "23218", "name_kanji": "木檜 龍馬", "name_kana": "こぐれ りょうま", "status": "在籍", "gender": "M"},
    {"serial": 16, "student_id": "23219", "name_kanji": "齋藤 光輝", "name_kana": "さいとう こうき", "status": "在籍", "gender": "M"},
    {"serial": 17, "student_id": "23220", "name_kanji": "齋藤 暖", "name_kana": "さいとう はる", "status": "在籍", "gender": "F"},
    {"serial": 18, "student_id": "23221", "name_kanji": "里見 仁翔", "name_kana": "さとみ じんと", "status": "在籍", "gender": "M"},
    {"serial": 19, "student_id": "23222", "name_kanji": "清水 大夢", "name_kana": "しみず ひろむ", "status": "在籍", "gender": "M"},
    {"serial": 20, "student_id": "23224", "name_kanji": "新 大和", "name_kana": "しん やまと", "status": "在籍", "gender": "M"},
    {"serial": 21, "student_id": "23225", "name_kanji": "髙山 空", "name_kana": "たかやま そら", "status": "在籍", "gender": "M"},
    {"serial": 22, "student_id": "23226", "name_kanji": "竹中 碧", "name_kana": "たけなか あおい", "status": "在籍", "gender": "M"},
    {"serial": 23, "student_id": "23227", "name_kanji": "多胡 晴陽", "name_kana": "たご はるひ", "status": "在籍", "gender": "M"},
    {"serial": 24, "student_id": "23228", "name_kanji": "田島 向日葵", "name_kana": "たじま ひまり", "status": "在籍", "gender": "F"},
    {"serial": 25, "student_id": "23229", "name_kanji": "塚越 彩英", "name_kana": "つかごし さえ", "status": "在籍", "gender": "F"},
    {"serial": 26, "student_id": "23230", "name_kanji": "塚本 賢介", "name_kana": "つかもと けんすけ", "status": "在籍", "gender": "M"},
    {"serial": 27, "student_id": "23231", "name_kanji": "辻澤 拓也", "name_kana": "つじさわ たくや", "status": "休学", "gender": "M"},
    {"serial": 28, "student_id": "23232", "name_kanji": "長谷川 瑠万", "name_kana": "はせがわ るま", "status": "在籍", "gender": "M"},
    {"serial": 29, "student_id": "23233", "name_kanji": "平林 皐", "name_kana": "ひらばやし さつき", "status": "在籍", "gender": "M"},
    {"serial": 30, "student_id": "23234", "name_kanji": "堀越 陽葵", "name_kana": "ほりこし ひなた", "status": "在籍", "gender": "F"},
    {"serial": 31, "student_id": "23235", "name_kanji": "松原 想悟", "name_kana": "まつばら そうご", "status": "在籍", "gender": "M"},
    {"serial": 32, "student_id": "23236", "name_kanji": "黛 陽翔", "name_kana": "まゆずみ あきと", "status": "在籍", "gender": "M"},
    {"serial": 33, "student_id": "23237", "name_kanji": "安原 大成", "name_kana": "やすはら たいせい", "status": "在籍", "gender": "M"},
    {"serial": 34, "student_id": "23238", "name_kanji": "山口 瑛翔", "name_kana": "やまぐち えいと", "status": "在籍", "gender": "M"},
    {"serial": 35, "student_id": "23239", "name_kanji": "山田 桔平", "name_kana": "やまだ きっぺい", "status": "在籍", "gender": "M"},
    {"serial": 36, "student_id": "23240", "name_kanji": "山田 健寛", "name_kana": "やまだ たけひろ", "status": "在籍", "gender": "M"},
    {"serial": 37, "student_id": "23241", "name_kanji": "山本 理駆", "name_kana": "やまもと りく", "status": "在籍", "gender": "M"},
    {"serial": 38, "student_id": "23242", "name_kanji": "吉原 郁", "name_kana": "よしはら いく", "status": "在籍", "gender": "M"},
    {"serial": 39, "student_id": "22217", "name_kanji": "栗本 悠貴", "name_kana": "くりもと ゆうき", "status": "在籍", "gender": "M"},
    {"serial": 40, "student_id": "22219", "name_kanji": "坂口 正樹", "name_kana": "さかぐち まさき", "status": "在籍", "gender": "M"},
    {"serial": 41, "student_id": "22220", "name_kanji": "佐藤 広隆", "name_kana": "さとう ひろたか", "status": "在籍", "gender": "M"},
    {"serial": 42, "student_id": "22223", "name_kanji": "住谷 志誠", "name_kana": "すみや ゆきなり", "status": "在籍", "gender": "M"},
    {"serial": 43, "student_id": "21214", "name_kanji": "剱持 菜苗", "name_kana": "けんもち ななえ", "status": "休学", "gender": "F"},
    {"serial": 44, "student_id": "21219", "name_kanji": "坂上 一輝", "name_kana": "さかうえ かずき", "status": "在籍", "gender": "M"},
]

COMMITTEES = [
    ("学級委員", ["浅野 悠里子", "川田 律貴"]),
    ("会計委員", ["里見 仁翔", "清水 大夢"]),
    ("図書委員", ["堀越 陽葵"]),
    ("文化委員", ["齋藤 暖"]),
    ("体育委員", ["新 大和", "髙山 空"]),
    ("群嶺委員", ["山田 健寛"]),
    ("新聞委員", ["田島 向日葵", "塚越 彩英"]),
    ("環境委員", ["多胡 晴陽", "倉田 楽翔"]),
    ("選挙管理委員", ["坂上 一輝"]),
]
